### ISSUE TITLE
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded

### ISSUE THREAD

**Issue by zehawki** [onurzorluer/react-image-file-resizer#39]
**Describe the bug**
When a webp image is given to this module, it throws the following error:

index.js:96 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Function.value (xyz.chunk.js:105:22)
    at Image.t.onload (xyz.chunk.js:128:19)

The first error goes to:

`for (var n = atob(e.toString().replace(/^data:image\/(png|jpeg|jpg);base64,/, "")), r = [], a = 0; a < n.length; a += 512) {`

The 2nd error goes to:

`c = e.b64toBlob(d, "image/".concat(a)), u("blob" === l ? c : d);`

And the callback foo is not called.

**To Reproduce**
1. Take some webp image (eg https://www.gstatic.com/webp/gallery/1.webp)
2.  props: maxWidth = 800, maxHeight = 1000, type = WEBP

**Expected behavior**
1. Should get a webp image back after processing

**Comment by cdelfierro** [comment]
This problem occurs whether the source is a webp, png or jpg and we excpect a webp as a result

**Comment by mohesem** [comment]
so it can't convert anything to webp?!

**Comment by cdelfierro** [comment]
> so it can't convert anything to webp?!

Until it gets fixed, i am afraid not

**Comment by zehawki** [comment]
Its rather sad but this library has open issues at the moment that makes it quite a bit unuseful - This one, then #40, then #30. I've now fully switched over to https://fengyuanchen.github.io/compressorjs/ after through testing and it works remarkably well
